-- Relatório Detalhado Avaliações e Questões (simulado): 

SELECT  UK.CD_USUARIOVEC, 
-- U.DS_LOGIN AS 'LOGIN', 
U.ID_IDENTIFICADOR AS 'IDENTIFICADOR USUÁRIO', U.DS_USUARIO AS 'NOME COMPLETO'
 , (CASE U.ID_SITUACAO WHEN 0 THEN 'Ativo' WHEN 1 THEN 'Inativo' END) AS 'SITUAÇÃO', UNI.NM_UNIDADE AS 'UNIDADE' 
-- , (SELECT CAR.NM_CARGO FROM TB_CARGO CAR WHERE CAR.CD_CARGO=UK.CD_CARGO) AS 'CARGO' 
 , C.CD_CURSO 
 , C.ID_SIGLA AS 'CÓDIGO CURSO'  , C.NM_CURSO AS 'CURSO' 
 , T.CD_TURMA 
 , T.DS_TURMA AS 'TURMA' 
-- , GROUP_CONCAT(DISTINCT UT.DS_USUARIO ORDER BY UT.DS_USUARIO SEPARATOR '; ') AS 'RESPONSÁVEIS' 
-- , SEC_TO_TIME(C.NR_CARGAHORARIA*60) AS 'CARGA HORÁRIA CURSO' 
 , M.CD_MATRICULA AS MATRICULA 
 , (CASE M.ID_STATUSMATRICULA 
    WHEN 0 THEN 'Matriculado'    WHEN 1 THEN 'Concluído'    WHEN 2 THEN 'Lista de Espera'     WHEN 3 THEN 'Solicitado'     WHEN 4 THEN 'Rejeitado' 
    WHEN 5 THEN 'Cancelado'    WHEN 6 THEN 'Solicitação Cancelada'     WHEN 7 THEN 'Excluído da Lista de Espera'     WHEN 8 THEN 'Excluída' 
    WHEN 9 THEN 'Pendente'    WHEN 10 THEN 'Aguardando Pagamento' END) AS 'Status Matrícula' 
 , (CASE M.ID_STATUSAPROVEITAMENTO 
    WHEN 0 THEN 'Pendente'     WHEN 1 THEN 'Aprovado'     WHEN 2 THEN 'Reprovado' END) AS 'Status Aproveitamento' 
 , CAST(M.NR_ANDAMENTO AS DECIMAL (5,2)) AS 'ANDAMENTO', CAST( COALESCE(M.NR_FREQUENCIA,0) AS DECIMAL (5,2)) AS 'FREQUÊNCIA', CAST(M.NR_APROVEITAMENTO AS DECIMAL (5,2)) AS 'APROVEITAMENTO' 
 , DATE_FORMAT(M.DT_REALIZACAO, '%d/%m/%Y') AS 'REALIZAÇÃO MATRÍCULA', DATE_FORMAT(M.DT_FINALIZACAO, '%d/%m/%Y %H:%i:%s') AS 'CONCLUSÃO MATRÍCULA' 
-- , (SELECT SEC_TO_TIME(SUM(ICA.NR_TEMPOTOTAL)) FROM TB_ITEMCURSOACESSO ICA WHERE ICA.CD_MATRICULA = M.CD_MATRICULA) AS 'TEMPO TOTAL Matrícula' 
 
-- DETALHES DO ITEMCURSO:
 , IC.CD_ITEMCURSO
 , IC.NM_ITEMCURSO AS 'NOME AVALIAÇÃO (ItemCurso)' 
 , (CASE IC.ID_TIPO WHEN 1 THEN 'Tópico' 	WHEN 2 THEN 'Av Reação' 	WHEN 3 THEN 'Av Aprendizagem'
	WHEN 4 THEN 'Scorm' 	WHEN 5 THEN 'SCO' 	WHEN 6 THEN 'Video-Link'
	WHEN 7 THEN 'Certificado' 	WHEN 8 THEN 'Recurso' 	WHEN 9 THEN '?'
	WHEN 10 THEN 'Video-Upload' 	WHEN 11 THEN 'Auto Av' 	WHEN 12 THEN 'Apresentação'
	WHEN 13 THEN 'Podcast' END ) AS 'TIPO' 
 , IC.NR_TENTATIVASAVALIACAO AS 'Tentativas' 
-- , IC.NR_PESOCERTIFICACAO AS 'Peso'
 , (CASE IC.ID_TIPOCERTIFICACAO WHEN 0 THEN 'Nota (Scorm)' 		WHEN 1 THEN 'Andamento (Scorm)'
	WHEN 5 THEN 'Realização (geral)' 	WHEN 6 THEN 'Nota (Av Auto/Apr)'
	WHEN 7 THEN 'Realização (Av Re/Apr)'  END) AS 'MÉTRICA' 
 , IC.CD_OBJETOAPRENDIZAGEM AS 'ID OBJ' 
-- , ICH.CD_ITEMCURSOHISTORICO 
-- , (SELECT SEC_TO_TIME(SUM(ICA.NR_TEMPOTOTAL)) FROM TB_ITEMCURSOACESSO ICA WHERE ICA.CD_ITEMCURSO = IC.CD_ITEMCURSO AND ICA.CD_MATRICULA = M.CD_MATRICULA) AS 'Tempo Acesso na Avaliação' 
 , (CASE WHEN (ICH.NR_ANDAMENTO IS NULL) THEN 'Não iniciou' 	WHEN (ICH.NR_ANDAMENTO >= 100) THEN 'Completo' 	ELSE 'Em andamento' END ) AS 'Andamento Item' 
-- , DATE_FORMAT(ICH.DT_REGISTRO, '%d/%m/%Y %H:%i:%s') AS 'Acesso ao Item', DATE_FORMAT(ICH.DT_CONCLUSAO_ANDAMENTO, '%d/%m/%Y %H:%i:%s') AS 'Conclusão do Item' 
-- , CAST(ICH.NR_DESEMPENHO/10 AS DECIMAL (5,2)) AS 'Resultado' 
 , CAST(ICH.NR_CERTIFICACAO/10 AS DECIMAL (5,2)) AS 'Nota Final Avaliação' 

-- DETALHES DAS TENTATIVAS: 
 , UAV.CD_USUARIOAVALIACAOLMS AS 'ID Tentativa' 
 , UAV.ID_TENTATIVA AS 'Tentativa #' 
-- , (CASE UAV.ID_TENTATIVA_ATUAL WHEN 1 THEN 'Sim' ELSE 'Não' END) AS 'Tentativa Atual' 
 , DATE_FORMAT(UAV.DT_REGISTRO, '%d/%m/%Y %H:%i:%s') AS 'Acesso Tentativa', DATE_FORMAT(UAV.DT_ULTIMAMODIFICACAO, '%d/%m/%Y %H:%i:%s') AS 'Atualização' 
 , CAST(UAV.NR_NOTA AS DECIMAL (5,2)) AS 'Nota Tentativa' 
 , (CASE WHEN (UAV.ID_PENDENTE=1 OR UAV.CD_USUARIOAVALIACAOLMS IS NULL) THEN 'Não finalizada' 	WHEN UAV.ID_NOTAPENDENTE=1 THEN 'Correção Pendente' 	ELSE '-' END) AS 'Pendência' 

-- DETALHES DE CADA QUESTÃO DA PROVA: 
-- , UQ.CD_USUARIOQUESTAOLMS 
 , UQ.CD_QUESTAOLMS AS 'ID QUESTÃO' 
-- , (CASE IQ.ID_SITUACAO WHEN 0 THEN 'Inativa' WHEN 1 THEN 'Ativa' ELSE '-' END) AS 'Situação Questão' 
 , CONCAT(UQ.ID_POSICAO, ') ', COALESCE(IQ.DS_ENUNCIADO_FILTRO, IQ.DS_ENUNCIADO)) AS ENUNCIADO --	, UQ.DS_ENUNCIADO AS 'Enunciado Recebido'
 , (CASE UQ.ID_TIPOQUESTAO WHEN 0 THEN 'Objetiva' WHEN 1 THEN 'Múltipla Escolha' WHEN 2 THEN 'Verdadeira/Falsa' WHEN 3 THEN 'Dissertativa' 
		WHEN 4 THEN 'Escala' WHEN 5 THEN 'Entrega de Trabalho' WHEN 6 THEN 'Nota Atribuída' 
		WHEN 7 THEN (CASE UQ.ID_TEXTOSIMPLES WHEN 0 THEN 'Valor Numérico' WHEN 1 THEN 'Texto Simples' END) 
		WHEN 8 THEN 'Associativa' WHEN 9 THEN 'Completar Lacuna' ELSE '?' END) AS 'TIPO QUESTAO' 
 , (CASE UQ.ID_RESPONDIDA WHEN 1 THEN 'Sim' ELSE 'Não' END) AS 'Respondida' 
 , IF(IC.ID_TIPO=2,'', CAST(UQ.NR_DESEMPENHO/10 AS DECIMAL(5,2)) ) AS 'Nota da Questão' 
-- , CAST( UQ.NR_DESEMPENHO/10 AS DECIMAL(5,2)) AS 'Nota da Questão' 

-- ALTERNATIVAS RESPONDIDAS: 
-- , GROUP_CONCAT(DISTINCT UALT.CD_USUARIOALTERNATIVALMS), GROUP_CONCAT(DISTINCT UALT.CD_ALTERNATIVAQUESTAO) 
 , (CASE WHEN UQ.ID_TIPOQUESTAO = 3 THEN UQ.DS_RESPOSTA 		-- Dissertativa 
 	WHEN UQ.ID_TIPOQUESTAO = 4 THEN UQ.NR_RESPOSTA_ESCALA 	-- Escala 
 	WHEN UQ.ID_TIPOQUESTAO = 5 THEN CONCAT('Arquivo: ',UQ.DS_NOMEARQUIVO) 	-- Entrega Trabalho 
	WHEN UQ.ID_TIPOQUESTAO = 6 THEN UQ.NR_DESEMPENHO/10 		-- Nota Atribuída 
	WHEN UQ.ID_TIPOQUESTAO IN (0, 1, 2, 8) 
		THEN REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( 
			REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( 
				REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( 
					REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( 
						REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( 
							REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( 
								REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( 
		GROUP_CONCAT( DISTINCT CONCAT( (CASE UQ.ID_TIPOQUESTAO 
			WHEN 2 THEN CONCAT( IF(UALT.ID_CORRETA = UALT.ID_ESCOLHIDACORRETA, '[C]- ', '[E]- ') , (CASE UALT.ID_ESCOLHIDACORRETA WHEN 0 THEN '[F] ' WHEN 1 THEN '[V] ' END), UALT.DS_ALTERNATIVA ) 	-- Verdadeira/Falsa 
			WHEN 8 THEN CONCAT( (CASE UALT.ID_ESCOLHIDACORRETA WHEN 1 THEN '[C]- ' WHEN 0 THEN '[E]- ' END), UALT.DS_ALTERNATIVA, '[', UAS.DS_DESCRICAO, ']' ) 	-- Asociativa 
			ELSE CONCAT( IF(IC.ID_TIPO = 3, (CASE UALT.ID_CORRETA WHEN 0 THEN '[E]- ' WHEN 1 THEN '[C]- ' END), ''), UALT.DS_ALTERNATIVA) END) 	-- Objetiva / Múltipla Escolha 
			 ) ORDER BY UALT.ID_POSICAO SEPARATOR '; ')	
		, '&aacute;','á') ,'&acirc;','â') ,'&atilde;','ã') ,'&agrave;','à') ,'&auml;','ä') ,'&Aacute;','Á') ,'&Acirc;','Â') ,'&Atilde;','Ã') ,'&Agrave;','À'), '&Auml;','Ä') 
	 ,'&ccedil;','ç') ,'&Ccedil;','Ç') ,'&eacute;','é') ,'&ecirc;','ê') ,'&egrave;','è') ,'&euml;','ë') ,'&Eacute;','É') ,'&Ecirc;','Ê') ,'&Egrave;','È') ,'&Euml;','Ë') 
	 ,'&iacute;','í') ,'&Iacute;','Í') ,'&icirc;','î') ,'&Icirc;','Î') ,'&igrave;','ì') ,'&Igrave;','Ì') ,'&iuml;','ï') ,'&Iuml;','Ï') ,'&ntilde;','ñ') ,'&Ntilde;','Ñ') 
	 ,'&oacute;','ó') ,'&ocirc;','ô') ,'&otilde;','õ') ,'&ograve;','ò') ,'&ouml;','ö') ,'&Oacute;','Ó') ,'&Ocirc;','Ô') ,'&Otilde;','Õ') ,'&Ograve;','Ò') ,'&Ouml;','Ö') 
	 ,'&uacute;','ú') ,'&ucirc;','û') ,'&ugrave;','ù') ,'&uuml;','ü') ,'&Uacute;','Ú') ,'&Ucirc;','Û') ,'&Ugrave;','Ù') ,'&Uuml;','Ü') ,'&ldquo;','“') ,'&rdquo;','”') 
	 ,'&quot;','"') ,'\t','   ') ,'&ndash;','-') ,'&nbsp;',' ') ,'<p>','') ,'</p>',' ') ,'<strong>','') ,'</strong>','') ,'<var>','') ,'</var>','') 
	 ,'<span>','') ,'</span>','') ,'<u>','') ,'</u>','') ,'<p style="text-align:justify">','') , '<span style="font-family:arial,helvetica,sans-serif; font-size:16px">','') ,'<span style="font-family:arial,helvetica,sans-serif">','') ,'<span style="font-size:16px">','')
	WHEN UQ.ID_TIPOQUESTAO = 7 THEN UQ.DS_RESPOSTA 	-- Texto simples/numérico 
	WHEN UQ.ID_TIPOQUESTAO = 9 	-- Completar Lacuna 
		THEN GROUP_CONCAT( (CASE UALTLAC.ID_TIPOLACUNA WHEN 0 THEN UALTLAC.DS_ALTERNATIVA WHEN 1 THEN CONCAT( IF(UALTLAC.ID_ESCOLHIDACORRETA=1, '[C]-', '[E]-'), '[',UALTLAC.DS_RESPOSTA,']') WHEN 2 THEN '\n' ELSE '-' END) ORDER BY UALTLAC.ID_POSICAO SEPARATOR ' ') 
	ELSE '...' END) AS RESPOSTA 
FROM TB_CURSO C INNER JOIN TB_TURMA T ON T.ID_CURSO=C.CD_CURSO --	AND C.CD_CURSO BETWEEN 3001 AND 3500
INNER JOIN TB_MATRICULA M ON M.ID_TURMA=T.CD_TURMA 
INNER JOIN TB_USUARIO_KONVIVA UK ON UK.CD_USUARIOVEC=M.ID_USUARIOVEC 
INNER JOIN TB_USUARIO U ON U.CD_USUARIO=UK.CD_USUARIO 
INNER JOIN TB_USUARIO_PERFIL_UNIDADE UPU ON UPU.CD_USUARIOVEC=UK.CD_USUARIOVEC AND UPU.CD_PERFIL=2 
INNER JOIN TB_UNIDADE UNI ON UNI.CD_UNIDADE = UPU.CD_UNIDADE 
INNER JOIN TB_ITEMCURSO IC ON IC.CD_CURSO=C.CD_CURSO AND IC.ID_TIPO IN (2,3,11) -- 11 AutoAv fora 
INNER JOIN TB_ITEMCURSOHISTORICO ICH ON ICH.CD_ITEMCURSO=IC.CD_ITEMCURSO AND ICH.CD_MATRICULA=M.CD_MATRICULA 
/*	LEFT JOIN ( 
		(SELECT 'TIns' AS TIPO, TI.CD_TURMA, TI.CD_INSTRUTOR AS USUARIO , NULL AS ARE FROM TB_TURMA_INSTRUTORES TI) UNION 
		(SELECT 'TMon' AS TIPO, TM.CD_TURMA, TM.CD_MONITOR AS USUARIO , NULL AS ARE FROM TB_TURMA_MONITORES TM) UNION 
		(SELECT 'TRes' AS TIPO, TR.CD_TURMA, TR.CD_RESPONSAVEL AS USUARIO , NULL AS ARE FROM TB_TURMA_RESPONSAVEIS TR) UNION 
		(SELECT 'TTut' AS TIPO, TT.CD_TURMA, TT.CD_TUTOR AS USUARIO , NULL AS ARE FROM TB_TURMA_TUTORES TT) 
		
		UNION (SELECT 'AIns' AS TIPO, A2.ID_TURMA AS CD_TURMA, AI.CD_INSTRUTOR AS USUARIO , A2.CD_AULA AS ARE FROM TB_AULA_INSTRUTORES AI INNER JOIN TB_AULA A2 ON A2.CD_AULA=AI.CD_AULA ) 
		UNION (SELECT 'REMod' AS TIPO, RE2.ID_TURMA AS CD_TURMA, REMOD.CD_MODERADOR AS USUARIO , RE2.CD_REUNIAO AS ARE FROM TB_REUNIAO_MODERADOR REMOD INNER JOIN TB_REUNIAO RE2 ON RE2.CD_REUNIAO=REMOD.CD_REUNIAO) 
	) USERS ON USERS.CD_TURMA = T.CD_TURMA
--		AND IF(USERS.ARE IS NULL, 1=1, USERS.ARE = A.CD_AULA OR USERS.ARE = RE.CD_REUNIAO)
	LEFT JOIN TB_USUARIO_KONVIVA UKT ON UKT.CD_USUARIOVEC=USERS.USUARIO 
	LEFT JOIN TB_USUARIO UT ON UT.CD_USUARIO=UKT.CD_USUARIO */
LEFT JOIN TB_USUARIO_AVALIACAOLMS UAV ON UAV.CD_MATRICULA=M.CD_MATRICULA AND UAV.CD_ITEMCURSO=IC.CD_ITEMCURSO 
LEFT JOIN TB_USUARIO_QUESTAOLMS UQ ON UQ.CD_USUARIOAVALIACAOLMS = UAV.CD_USUARIOAVALIACAOLMS 
LEFT JOIN TB_ITEMAVALIACAO_QUESTAO IQ ON IQ.CD_ITEMAVALIACAO = UQ.CD_QUESTAOLMS 
LEFT JOIN TB_USUARIO_ALTERNATIVAQUESTAOLMS UALT ON UALT.CD_USUARIOQUESTAOLMS = UQ.CD_USUARIOQUESTAOLMS AND UALT.ID_SELECIONADA = 1 
LEFT JOIN TB_USUARIO_ALTERNATIVA_ASSOCIATIVA UAS ON UAS.CD_USUARIOQUESTAOLMS = UALT.CD_USUARIOQUESTAOLMS AND UALT.CD_ASSOCIATIVASELECIONADA = UAS.CD_USUARIOASSOCIATIVA AND UQ.ID_TIPOQUESTAO=8 
LEFT JOIN TB_USUARIO_ALTERNATIVAQUESTAOLMS UALTLAC ON UALTLAC.CD_USUARIOQUESTAOLMS = UQ.CD_USUARIOQUESTAOLMS /* AND UALTLAC.ID_TIPOLACUNA != 2 */ AND UQ.ID_TIPOQUESTAO = 9 

WHERE 1=1 
	AND C.CD_CURSO IN (905) -- BETWEEN 601 AND 1000
--	AND IC.ID_TIPO IN (2)
--	AND T.CD_TURMA IN (6, 324) 
--	AND UK.CD_USUARIOVEC = 2 
--	AND M.ID_STATUSMATRICULA IN (0,1) 
--	AND M.CD_MATRICULA IN (1681063,  708256,710806,1276658,1379130,1660033) -- 110646, 110052) 
--	AND UQ.CD_QUESTAOLMS IN (627, 381, 447, 402) 
--	AND UQ.ID_TIPOQUESTAO = 8 AND UQ.ID_RESPONDIDA = 1
--	AND UAV.CD_AVALIACAOLMS = 772 
--	AND DATE(UAV.DT_REGISTRO) >= '2021-02-05' 
GROUP BY M.CD_MATRICULA, UAV.CD_USUARIOAVALIACAOLMS, UQ.CD_USUARIOQUESTAOLMS 
ORDER BY  C.NM_CURSO, C.CD_CURSO, T.CD_TURMA, U.DS_USUARIO, UK.CD_USUARIOVEC, M.CD_MATRICULA, IC.ID_ORDEMAPRESENTACAO 
	,  UAV.CD_USUARIOAVALIACAOLMS, UQ.ID_POSICAO, /* CD_QUESTAOLMS, */ UALT.ID_POSICAO 
;


/* SELECT * FROM TB_OBJAPRENDIZAGEM O WHERE O.ID_TIPO LIKE '%avalia%' -- CD_OBJETOAPRENDIZAGEM = 11546
;
SELECT COUNT(*) FROM TB_USUARIO_AVALIACAOLMS ;
SELECT COUNT(*) FROM TB_USUARIO_ALTERNATIVAQUESTAOLMS; */