-- EXTRAIR AVALIAÇÃO

-- AVALIAÇÕES REAÇÃO:
SELECT  O.CD_OBJETOAPRENDIZAGEM AS 'ID AVALIAÇÃO', 
O.NM_OBJETOAPRENDIZAGEM AS 'AVALIAÇÃO', 
 O.ID_TIPO AS 'TIPO AVALIAÇÃO', O.DT_CADASTRO AS 'DATA CADASTRO', 
 (CASE O.ID_SITUACAO WHEN 0 THEN 'INATIVA' WHEN 1 THEN 'ATIVA' END) AS 'SITUAÇÃO AVALIAÇÃO',
/* (SELECT COUNT(DISTINCT OUNI.CD_UNIDADE) FROM TB_OBJAPRENDIZAGEM_UNIDADE_ADMIN OUNI 
 	 WHERE OUNI.CD_OBJETOAPRENDIZAGEM=O.CD_OBJETOAPRENDIZAGEM GROUP BY O.CD_OBJETOAPRENDIZAGEM) AS 'QNT UNIDADES DE ADMIN',
 (SELECT GROUP_CONCAT(CONCAT(IFNULL(UNI.NM_UNIDADE,''),'/Cod: "',IFNULL(UNI.DS_CODIGO,''),'"') ORDER BY UNI.ID_HIERARQUIA SEPARATOR ' |' ) 
 	 FROM TB_OBJAPRENDIZAGEM_UNIDADE_ADMIN OUNI INNER JOIN TB_UNIDADE UNI ON OUNI.CD_UNIDADE=UNI.CD_UNIDADE 
	 WHERE OUNI.CD_OBJETOAPRENDIZAGEM=O.CD_OBJETOAPRENDIZAGEM GROUP BY O.CD_OBJETOAPRENDIZAGEM) AS 'UNIDADES DE ADMIN (Nome,Código)', */
 (SELECT COUNT(DISTINCT IC.CD_CURSO) FROM TB_ITEMCURSO IC WHERE IC.CD_OBJETOAPRENDIZAGEM=O.CD_OBJETOAPRENDIZAGEM) AS 'QNT CURSOS ASSOCIADOS', 
/* (SELECT GROUP_CONCAT(DISTINCT C.CD_CURSO, ' Cod: "',IFNULL(C.ID_SIGLA,''),'"' ORDER BY C.NM_CURSO SEPARATOR ' |' ) 
 	 FROM TB_ITEMCURSO IC INNER JOIN TB_CURSO C ON C.CD_CURSO=IC.CD_CURSO 
	 WHERE IC.CD_OBJETOAPRENDIZAGEM=O.CD_OBJETOAPRENDIZAGEM GROUP BY IC.CD_OBJETOAPRENDIZAGEM) AS 'CURSOS ASSOCIADOS (ID,Código)', */
-- OAVA2.CD_AVALIACAOLMS,
 AVA.DS_AVALIACAO AS 'DESCRIÇÃO AVALIAÇÃO', AVA.DS_FEEDBACK_GERAL AS 'FEEDBACK GERAL',
 AVAI.NR_POSICAO AS 'POSIÇÃO ITEM', 
-- IA.CD_ITEMAVALIACAO, 
 IA.ID_TIPO AS 'TIPO ITEM', -- IA.DS_TITULO AS 'TITULO GRUPO',

-- CATQ.CD_CATEGORIAQUESTAO,
CATQ.DS_TITULO AS 'CATEGORIA QUESTÃO', (SELECT CAT2.DS_TITULO FROM TB_CATEGORIAQUESTAO CAT2 WHERE CAT2.CD_CATEGORIAQUESTAO=CATQ.CD_RAIZ) AS 'CATEGORIA RAIZ',
IQ.CD_ITEMAVALIACAO AS 'ID QUESTÃO', IQ.DS_ENUNCIADO_FILTRO AS 'ENUNCIADO (texto)', IQ.DS_ENUNCIADO AS 'ENUNCIADO (formatado)', 
(CASE IQ.ID_SITUACAO WHEN 0 THEN 'Inativa' WHEN 1 THEN 'Ativa' ELSE '-' END) AS 'SITUAÇÃO QUESTÃO', 
(CASE IQ.ID_TIPOQUESTAO WHEN 0 THEN 'Objetiva' WHEN 1 THEN 'Múltipla Escolha' WHEN 3 THEN 'Dissertativa' WHEN 4 THEN 'Escala' END) AS 'TIPO QUESTÃO',
-- (CASE IQ.ID_OBRIGATORIO WHEN 1 THEN 'Sim' ELSE 'Não' END) AS 'OBRIGATORIA',
IF(IQ.ID_TIPOQUESTAO = 4, IQ.NR_ESCALA, '-') AS 'ESCALA MÁXIMA',
(CASE IQ.ID_NUMERACAO WHEN 0 THEN 'a,b,c' WHEN 1 THEN 'A,B,C' WHEN 2 THEN '1,2,3' WHEN 3 THEN 'I,II,III' ELSE '-' END) AS 'NUMERAÇÃO DAS ALTERNATIVAS',
-- ALTQ.CD_ALTERNATIVAQUESTAO, 
(CASE WHEN IQ.ID_TIPOQUESTAO NOT IN (3,4,5,6) THEN ALTQ.ID_POSICAO ELSE '-' END) AS 'POSIÇÃO DA ALTERNATIVA',
(CASE WHEN IQ.ID_TIPOQUESTAO NOT IN (3,4,5,6) THEN ALTQ.DS_ALTERNATIVA ELSE '-' END) AS 'DESCRIÇÃO DA ALTERNATIVA' 
-- (CASE WHEN IQ.ID_TIPOQUESTAO NOT IN (3,4,5,6) THEN IF(ALTQ.DS_ALTERNATIVA_TEXT IS NOT NULL AND ALTQ.DS_ALTERNATIVA_TEXT != '', ALTQ.DS_ALTERNATIVA_TEXT, ALTQ.DS_ALTERNATIVA) ELSE '-' END) AS 'DESCRIÇÃO DA ALTERNATIVA' 

FROM TB_OBJAPRENDIZAGEM O 
INNER JOIN TB_OBJAPRENDIZAGEM_AVALIACAOREACAO OAVA2 ON OAVA2.CD_OBJETOAPRENDIZAGEM=O.CD_OBJETOAPRENDIZAGEM AND O.ID_TIPO LIKE 'AVALIACAO_REACAO'
INNER JOIN TB_AVALIACAOLMS AVA ON AVA.CD_AVALIACAOLMS=OAVA2.CD_AVALIACAOLMS
  LEFT JOIN TB_AVALIACAOLMS_ITEMAVALIACAO AVAI ON AVAI.CD_AVALIACAOLMS = AVA.CD_AVALIACAOLMS
  LEFT JOIN TB_ITEMAVALIACAO IA ON IA.CD_ITEMAVALIACAO = AVAI.CD_ITEMAVALIACAO
  LEFT JOIN TB_ITEMAVALIACAO_QUESTAO IQ ON IQ.CD_ITEMAVALIACAO=IA.CD_ITEMAVALIACAO AND IQ.ID_TIPOQUESTAO IN (0, 1, 3, 4) /* Objetiva, MultiplaEscolha, Dissertativa, Escala */ 
  LEFT JOIN TB_CATEGORIAQUESTAO CATQ ON CATQ.CD_CATEGORIAQUESTAO=IQ.CD_CATEGORIAQUESTAO
  LEFT JOIN TB_ALTERNATIVAQUESTAO ALTQ ON ALTQ.CD_QUESTAOLMS = IQ.CD_ITEMAVALIACAO AND IQ.ID_TIPOQUESTAO IN (0, 1)
-- WHERE O.CD_OBJETOAPRENDIZAGEM IN (3496) 
-- WHERE O.NM_OBJETOAPRENDIZAGEM LIKE '%%'
-- GROUP BY O.CD_OBJETOAPRENDIZAGEM
ORDER BY O.NM_OBJETOAPRENDIZAGEM, AVAI.NR_POSICAO, ALTQ.ID_POSICAO
;